import { Hind_Siliguri } from "next/font/google";
import "./globals.css";

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-arp="">
      <body
        
        data-new-gr-c-s-check-loaded="14.1244.0"
        
        data-gr-ext-installed=""
        className={`${hindSiliguri.variable}  antialiased `}
      >
        
          {children}
       
      </body>
    </html>
  );
}
