import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { Toaster } from "sonner";


const Providers = dynamic(() => import('@/lib/providers'));
const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-arp="">
      <body
        
        data-new-gr-c-s-check-loaded="14.1244.0"
        
        data-gr-ext-installed=""
        className={`${hindSiliguri.variable}  antialiased `}
      >
        
        <Providers>
          {children}
        </Providers>
         <Toaster />
      </body>
    </html>
  );
}
